### ISSUE TITLE
add basic scaffolding to make it possible to have posts there

### ISSUE THREAD

**Issue by rom1504** [rom1504/rom1504.github.io#1]
what's the easiest way ?

react + md module ?
lit + md module?

**Comment by rom1504** [comment]
follow https://simondosda.github.io/posts/2021-09-15-blog-github-pages-3-content.html

**Comment by danfergo** [comment]
just followed the rabbit til your github page and noticed this pull request.
 
I use Hexo with a few plugins. it works decently.
https://github.com/danfergo/danfergo.github.io/tree/backend

**Comment by rom1504** [comment]
let's copy https://github.com/karpathy/karpathy.github.io/tree/master

**Comment by rom1504** [comment]
going with custom lit (eg writing it myself), #2
